export const keyList = [
    //// 2 octave ///
    {
        note: "C2",
        enharmonic: "B#2",
        color: "white",
        label: "C",
        enharmoniclabel: "B#",
        midi: 72,
        shortcut: "q",
        position: 30,
    },
    {
        note: "C#2",
        enharmonic: "Db2",
        color: "black",
        label: "C#",
        enharmoniclabel: "Db",
        midi: 73,
        shortcut: "2",
        position: 30,
    },
    {
        note: "D2",
        enharmonic: false,
        color: "white",
        label: "D",
        enharmoniclabel: false,
        midi: 74,
        shortcut: "w",
        position: 29,
    },
    {
        note: "D#2",
        enharmonic: "Eb2",
        color: "black",
        label: "D#",
        enharmoniclabel: "Eb",
        midi: 75,
        shortcut: "3",
        position: 29,
    },
    {
        note: "E2",
        enharmonic: "Fb2",
        color: "white",
        label: "E",
        enharmoniclabel: "Fb",
        midi: 76,
        shortcut: "e",
        position: 28,
    },
    {
        note: "F2",
        enharmonic: "E#2",
        color: "white",
        label: "F",
        enharmoniclabel: "E#",
        midi: 77,
        shortcut: "r",
        position: 27,
    },
    {
        note: "F#2",
        enharmonic: "Gb2",
        color: "black",
        label: "F#",
        enharmoniclabel: "Gb",
        midi: 78,
        shortcut: "5",
        position: 27,
    },
    {
        note: "G2",
        enharmonic: false,
        color: "white",
        label: "G",
        enharmoniclabel: false,
        midi: 79,
        shortcut: "t",
        position: 26,
    },
    {
        note: "G#2",
        enharmonic: "Ab2",
        color: "black",
        label: "G#",
        enharmoniclabel: "Ab",
        midi: 80,
        shortcut: "6",
        position: 26,
    },
    {
        note: "A2",
        enharmonic: false,
        color: "white",
        label: "A",
        enharmoniclabel: false,
        midi: 81,
        shortcut: "y",
        position: 25,
    },
    {
        note: "A#2",
        enharmonic: "Bb2",
        color: "black",
        label: "A#",
        enharmoniclabel: "Bb",
        midi: 82,
        shortcut: "7",
        position: 25,
    },
    {
        note: "B2",
        enharmonic: "Cb2",
        color: "white",
        label: "B",
        enharmoniclabel: "Cb",
        midi: 83,
        shortcut: "u",
        position: 24,
    },

    /////3 Octave/////
    {
        note: "C3",
        enharmonic: false,
        color: "white",
        label: "C",
        enharmoniclabel: false,
        midi: 53,
        shortcut: "i",
        position: 23,
    },
    {
        note: "C#3",
        enharmonic: "Db3",
        color: "black",
        label: "C#",
        enharmoniclabel: "Db",
        midi: 61,
        shortcut: "9",
        position: 23,
    },
    {
        note: "D3",
        enharmonic: false,
        color: "white",
        label: "D",
        enharmoniclabel: false,
        midi: 74,
        shortcut: "o",
        position: 22,
    },
    {
        note: "D#3",
        enharmonic: "Eb3",
        color: "black",
        label: "D#",
        enharmoniclabel: "Eb",
        midi: 75,
        shortcut: "0",
        position: 22,
    },
    {
        note: "E3",
        enharmonic: "Fb3",
        color: "white",
        label: "E",
        enharmoniclabel: "Fb",
        midi: 64,
        shortcut: "p",
        position: 21,
    },
    {
        note: "F3",
        enharmonic: "E#3",
        color: "white",
        label: "F",
        enharmoniclabel: "E#",
        midi: 53,
        shortcut: "z",
        position: 20,
    },
    {
        note: "F#3",
        enharmonic: "Gb3",
        color: "black",
        label: "F#",
        enharmoniclabel: "Gb",
        midi: 54,
        shortcut: "s",
        position: 20,
    },
    {
        note: "G3",
        enharmonic: false,
        color: "white",
        label: "G",
        enharmoniclabel: false,
        midi: 55,
        shortcut: "x",
        position: 19,
    },
    {
        note: "G#3",
        enharmonic: "Ab3",
        color: "black",
        label: "G#",
        enharmoniclabel: "Ab",
        midi: 56,
        shortcut: "d",
        position: 19,
    },
    {
        note: "A3",
        enharmonic: false,
        color: "white",
        label: "A",
        enharmoniclabel: false,
        midi: 57,
        shortcut: "c",
        position: 18,
    },
    {
        note: "A#3",
        enharmonic: "Bb3",
        color: "black",
        label: "A#",
        enharmoniclabel: "Bb",
        midi: 58,
        shortcut: "f",
        position: 18,
    },
    {
        note: "B3",
        enharmonic: "Cb4",
        color: "white",
        label: "B",
        enharmoniclabel: "Cb",
        midi: 59,
        shortcut: "v",
        position: 17,
    },

    ////// 4 octave////
    {
        note: "C4",
        enharmonic: "B#3",
        color: "white",
        label: "C",
        enharmoniclabel: "B#",
        midi: 60,
        shortcut: "b",
        position: 16,
    },
    {
        note: "C#4",
        enharmonic: "Db4",
        color: "black",
        label: "C#",
        enharmoniclabel: "Db",
        midi: 61,
        shortcut: "h",
        position: 16,
    },
    {
        note: "D4",
        enharmonic: false,
        color: "white",
        label: "D",
        enharmoniclabel: false,
        midi: 62,
        shortcut: "n",
        position: 15,
    },
    {
        note: "D#4",
        enharmonic: "Eb4",
        color: "black",
        label: "D#",
        enharmoniclabel: "Eb",
        midi: 63,
        shortcut: "j",
        position: 15,
    },
    {
        note: "E4",
        enharmonic: "Fb4",
        color: "white",
        label: "E",
        enharmoniclabel: "Fb",
        midi: 64,
        shortcut: "m",
        position: 14,
    },
    {
        note: "F4",
        enharmonic: "E#4",
        color: "white",
        label: "F",
        enharmoniclabel: "E#",
        midi: 65,
        shortcut: ",",
        position: 13,
    },
    {
        note: "F#4",
        enharmonic: "Gb4",
        color: "black",
        label: "F#",
        enharmoniclabel: "Gb",
        midi: 66,
        shortcut: "l",
        position: 13,
    },
    {
        note: "G4",
        enharmonic: false,
        color: "white",
        label: "G",
        enharmoniclabel: false,
        midi: 67,
        shortcut: ".",
        position: 12,
    },
    {
        note: "G#4",
        enharmonic: "Ab4",
        color: "black",
        label: "G#",
        enharmoniclabel: "Ab",
        midi: 68,
        shortcut: ";",
        position: 12,
    },
    {
        note: "A4",
        enharmonic: false,
        color: "white",
        label: "A",
        enharmoniclabel: false,
        midi: 69,
        shortcut: "/",
        position: 11,
    },
    {
        note: "A#4",
        enharmonic: "Bb4",
        color: "black",
        label: "A#",
        enharmoniclabel: "Bb",
        midi: 70,
        shortcut: "'",
        position: 11,
    },
    {
        note: "B4",
        enharmonic: "Cb5",
        color: "white",
        label: "B",
        enharmoniclabel: "Cb",
        midi: 71,
        shortcut: "§",
        position: 10,
    },

    ///// 5 octave/////
    {
        note: "C5",
        enharmonic: "B#4",
        color: "white",
        label: "C",
        enharmoniclabel: "B#",
        midi: 72,
        shortcut: ";",
        position: 9,
    },
    {
        note: "C#5",
        enharmonic: "Db5",
        color: "black",
        label: "C#",
        enharmoniclabel: "Db",
        midi: 73,
        shortcut: "[",
        position: 9,
    },
    {
        note: "D5",
        enharmonic: false,
        color: "white",
        label: "D",
        enharmoniclabel: false,
        midi: 74,
        shortcut: "'",
        position: 8,
    },
    {
        note: "D#5",
        enharmonic: "Eb5",
        color: "black",
        label: "D#",
        enharmoniclabel: "Eb",
        midi: 75,
        shortcut: "]",
        position: 8,
    },
    {
        note: "E5",
        enharmonic: "Fb5",
        color: "white",
        label: "E",
        enharmoniclabel: "Fb",
        midi: 76,
        shortcut: "]",
        position: 7,
    },
    {
        note: "F5",
        enharmonic: "E#5",
        color: "white",
        label: "F",
        enharmoniclabel: "E#",
        midi: 77,
        shortcut: "]",
        position: 6,
    },
    {
        note: "F#5",
        enharmonic: "Gb5",
        color: "black",
        label: "F#",
        enharmoniclabel: "Gb",
        midi: 78,
        shortcut: "]",
        position: 6,
    },
    {
        note: "G5",
        enharmonic: false,
        color: "white",
        label: "G",
        enharmoniclabel: false,
        midi: 79,
        shortcut: "]",
        position: 5,
    },
    {
        note: "G#5",
        enharmonic: "Ab5",
        color: "black",
        label: "G#",
        enharmoniclabel: "Ab",
        midi: 80,
        shortcut: "]",
        position: 5,
    },
    {
        note: "A5",
        enharmonic: false,
        color: "white",
        label: "A",
        enharmoniclabel: false,
        midi: 81,
        shortcut: "]",
        position: 4,
    },
    {
        note: "A#5",
        enharmonic: "Bb5",
        color: "black",
        label: "A#",
        enharmoniclabel: "Bb",
        midi: 82,
        shortcut: "]",
        position: 4,
    },
    {
        note: "B5",
        enharmonic: "Cb6",
        color: "white",
        label: "B",
        enharmoniclabel: "Cb",
        midi: 83,
        shortcut: "]",
        position: 3,
    },
    ////// 6 octave ////
    {
        note: "E6",
        enharmonic: "Fb6",
        color: "white",
        label: "E",
        enharmoniclabel: "Fb",
        midi: 88,
        shortcut: "]",
        position: 0,
    },
    {
        note: "D#6",
        enharmonic: "Eb6",
        color: "black",
        label: "D#",
        midi: 89,
        shortcut: "]",
        position: 1,
    },
    {
        note: "D6",
        enharmonic: false,
        color: "white",
        label: "D",
        enharmoniclabel: false,
        midi: 90,
        shortcut: "]",
        position: 1,
    },
    {
        note: "C#6",
        enharmonic: "Db6",
        color: "black",
        label: "C",
        enharmoniclabel: "Db",
        midi: 91,
        shortcut: "]",
        position: 2,
    },
    {
        note: "C6",
        enharmonic: false,
        color: "white",
        label: "C",
        enharmoniclabel: false,
        midi: 92,
        shortcut: "]",
        position: 2,
    },
];
